### PR TITLE
💥 Implementation of Direction Catastrophe

### PR DESCRIPTION
**Pull request by Palwisha-18**

### CODE REVIEW

**Comment by ahmadjanan** [comment]
Should this program cancel opposite directions which are not next to each other in the input list? 
```
simplify_directions(['NORTH', 'EAST', 'SOUTH'])
```
returns
```
['NORTH', 'EAST', 'SOUTH']
```
Technically, it should cancel NORTH and SOUTH because we end up in the same position whether they are cancelled or not.

**Comment by Palwisha-18** [comment]
> Should this program cancel opposite directions which are not next to each other in the input list?
> 
> ```
> simplify_directions(['NORTH', 'EAST', 'SOUTH'])
> ```
> 
> returns
> 
> ```
> ['NORTH', 'EAST', 'SOUTH']
> ```
> 
> Technically, it should cancel NORTH and SOUTH because we end up in the same position whether they are cancelled or not.

If two consecutive directions are opposite then they should be cancelled. In this case ['NORTH', 'EAST', 'SOUTH'], the person  took North to go to (0,1) then went east (1,1) and lastly came to (1,0) by taking SOUTH.  As positions (0,1) and (1,0) are not equal, therefore we dont end up in the same position.

**Comment by ahmadjanan** [comment]
> > Should this program cancel opposite directions which are not next to each other in the input list?
> > ```
> > simplify_directions(['NORTH', 'EAST', 'SOUTH'])
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > returns
> > ```
> > ['NORTH', 'EAST', 'SOUTH']
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Technically, it should cancel NORTH and SOUTH because we end up in the same position whether they are cancelled or not.
> 
> If two consecutive directions are opposite then they should be cancelled. In this case ['NORTH', 'EAST', 'SOUTH'], the person took North to go to (0,1) then went east (1,1) and lastly came to (1,0) by taking SOUTH. As positions (0,1) and (1,0) are not equal, therefore we dont end up in the same position.

Let's break it down, step by step. If we don't cancel NORTH and SOUTH, it goes as following:
1. Starts at (0, 0)
2. NORTH (0, 1)
3. EAST (1, 1)
4. SOUTH (1, 0)
So START = (0, 0) and End = (1, 0)

Now, if we remove the opposite directions, it leaves us with `['EAST']`. So it becomes:
1. Starts at (0, 0)
2. EAST (1, 0)
Finally, START = (0, 0) and End = (1, 0)

The starting and ending points of both runs are the same. So I believe we should be cancelling out non-consecutive opposite directions as well.

**Comment by Palwisha-18** [comment]
@ahmadjanan I understand your explanation technically. But in a real-world scenario, suppose there is no actual way to get to (1,0) from (0,0). The road doesn't directly go there or is blocked. 
The example given in question statement also refers to only immediate opposite directions.

**Review by ahmadjanan — APPROVED** [review]
LGTM 👍

**Pull request merged**
